/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Source {
  path: string
  content: string
}
export interface Node {
  kind: string
}
export interface Problem {
  type: string
  message: string
}
export interface Config {
  esVersion: number
  rules: Record<string, (node: Node)=>Array<Problem>>
}
export function eschecker(sources: Array<Source>, config: Config): Array<Problem>
