/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function eschecker(sources: Array<Source>, config: Config): unknown | null
export class Source {
  path?: string
  content?: string
}
export class Config {
  esVersion?: number
  rules: Record<string, string>
}
