name: Publish

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - run: npx conventional-github-releaser -p angular
        continue-on-error: true
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.TOKEN}}
      - name: Install Dependencies
        run: yarn install
      
      - name: Build
        run: yarn build:packages
        
      - name: Publish
        run: yarn workspaces foreach -p run release --exclude internal-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
