name: TS-Publish

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.11.0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - run: npx conventional-github-releaser -p angular
        continue-on-error: true
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.TOKEN}}
      - name: Build
        run: pnpm build:packages
      - name: Publish
        run: pnpm run publish:ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
